### PR TITLE
Fix incorrect check for false values

### LINKED ISSUE #29: `false` saved as empty string, `true` stored as true
```js
const { convertArrayToCSV } = require('convert-array-to-csv');

let csv = convertArrayToCSV([
	[ 'valueIsTrue', 'valueIdFalse', 'valueIsTrueString', 'valueIsFalseString'],
	[ true, false, 'true', 'false' ]
]);

console.log(csv);
```

Output:

```csv
valueIsTrue,valueIdFalse,valueIsTrueString,valueIsFalseString
true,"",true,false
```

Expected Output:

```csv
valueIsTrue,valueIdFalse,valueIsTrueString,valueIsFalseString
true,false,true,false
```

### PR DESCRIPTION
**Pull request by ururk**
closes #29

### CODE REVIEW

**Comment by aichbauer** [comment]
Can you think of other falsy values that should be included in the here?

**Comment by ururk** [comment]
Your code already handles `null` and `undefined`, that leaves:

```javascript
0n
NaN
"" (empty string)
```

**Comment by ururk** [comment]
I'm pretty sure `NaN` will evaluate as expected (to an empty string?), as will `0n`. I think it might be useful to include those in a test.

**Comment by aichbauer** [comment]
Yep, we should definitively test this as well.

**Comment by ururk** [comment]
Adding them.

**Comment by ururk** [comment]
Ok - added!

**Comment by ururk** [comment]
Looks like it didn't like `0n` in the node 6/8 test runs, so I removed the check - it's only applicable to BigInt (node 10+ support) which when I test locally runs as expected.

**Comment by aichbauer** [comment]
Node 6 and 8 are actually pretty old... so we should consider moving to 10+, but that can be done later....

**Review by aichbauer — APPROVED** [review]

**Pull request merged**
